
reserves_population_files = {
  "Hirschfelden": ".\\data\\animal_population_0",
  "Layton Lake": ".\\data\\animal_population_1",
  "Medved Taiga": ".\\data\\animal_population_2",
  "Vurhonga Savanna": ".\\data\\animal_population_3",
  "Parque Fernando": ".\\data\\animal_population_4",
  "Yukon Valley": ".\\data\\animal_population_6",
  "Cuatro Colinas": ".\\data\\animal_population_8",
  "Silver Ridge Peaks": ".\\data\\animal_population_9",
  "Te Awaroa": ".\\data\\animal_population_10",
  "Rancho del Arroyo": ".\\data\\animal_population_11",
  "Mississippi Acres": ".\\data\\animal_population_12",
  "Revontuli Coast": ".\\data\\animal_population_13",
  "New England Mountains": ".\\data\\animal_population_14"
}

animaltypes_per_reserve = {
  "Hirschfelden": {
    0: "Wild Boar",
    1: "EU Rabbit",
    2: "Fallow Deer",
    3: "EU Bison",
    4: "Roe Deer",
    5: "Red Fox",
    6: "Pheasant",
    7: "Canada Goose",
    8: "Red Deer",
  },
  "Layton Lake": {
    0: "Moose",
    1: "Jackrabbit",
    2: "Mallard",
    3: "Merriam Turkey",
    4: "Black Bear",
    5: "Roosevelt Elk",
    6: "Coyote",
    7: "Blacktail Deer",
    8: "Whitetail Deer",
  },
  "Medved Taiga": {
    0: "Musk Deer",
    1: "Moose",
    2: "Wild Boar",
    3: "Reindeer",
    4: "EU Lynx",
    5: "Brown Bear",
    6: "W Capercaillie",
    7: "Grey Wolf",
  },
}

min_diamond_weight_per_animal = {
    "Canada Goose": 8.5,
    "EU Rabbit": 2.4,
    "Pheasant": 2.5,
    "Red Fox": 13.8,
    "Roe Deer": 33,
    "Fallow Deer": 96,
    "Wild Boar": 230,
    "Red Deer": 235,
    "EU Bison": 860,
    "Mallard": 2,
    "Merriam Turkey": 10.2,
    "Jackrabbit": 6,
    "Coyote": 26,
    "Blacktail Deer": 90,
    "Whitetail Deer": 95,
    "Black Bear": 260,
    "Moose": 600,
    "Roosevelt Elk": 480,
    "Musk Deer": 15,
    "Reindeer": 180,
    "EU Lynx": 40,
    "Brown Bear": 440,
    "W Capercaillie": 4.7,
    "Grey Wolf": 74,
}

max_diamond_weight_per_animal = {
    "Canada Goose": 9.2,
    "EU Rabbit": 2.6,
    "Pheasant": 3,
    "Red Fox": 15.4,
    "Roe Deer": 35,
    "Fallow Deer": 100,
    "Wild Boar": 240,
    "Red Deer": 240,
    "EU Bison": 920,
    "Mallard": 2.1,
    "Merriam Turkey": 11,
    "Jackrabbit": 6.83,
    "Coyote": 27,
    "Blacktail Deer": 95,
    "Whitetail Deer": 100,
    "Black Bear": 290,
    "Moose": 620,
    "Roosevelt Elk": 500,
    "Musk Deer": 17,
    "Reindeer": 182,
    "EU Lynx": 45,
    "Brown Bear": 482,
    "W Capercaillie": 5,
    "Grey Wolf": 80.3,
}

min_diamond_tr_per_animal = {
    "Canada Goose": 8.59,
    "EU Rabbit": 2.4,
    "Pheasant": 20.29,
    "Red Fox": 14.05,
    "Roe Deer": 81.86,
    "Fallow Deer": 251.72,
    "Wild Boar": 144.25,
    "Red Deer": 251.07,
    "EU Bison": 270.4,
    "Mallard": 19.62,
    "Merriam Turkey": 4.62,
    "Jackrabbit": 6.33,
    "Coyote": 56.87,
    "Blacktail Deer": 177.58,
    "Whitetail Deer": 255.09,
    "Black Bear": 22.8,
    "Moose": 274.99,
    "Roosevelt Elk": 380.84,
    "Musk Deer": 249,
    "Reindeer": 430.23,
    "EU Lynx": 27.68,
    "Brown Bear": 27.7,
    "W Capercaillie": 4.64,
    "Grey Wolf": 39,
}

max_diamond_tr_per_animal = {
    "Canada Goose": 9.2,
    "EU Rabbit": 2.6,
    "Pheasant": 22,
    "Red Fox": 15,
    "Roe Deer": 95,
    "Fallow Deer": 275,
    "Wild Boar": 160,
    "Red Deer": 272,
    "EU Bison": 300,
    "Mallard": 21,
    "Merriam Turkey": 4.8,
    "Jackrabbit": 6.8,
    "Coyote": 60,
    "Blacktail Deer": 230,
    "Whitetail Deer": 310,
    "Black Bear": 24,
    "Moose": 320,
    "Roosevelt Elk": 420,
    "Musk Deer": 276,
    "Reindeer": 470,
    "EU Lynx": 29,
    "Brown Bear": 30,
    "W Capercaillie": 5,
    "Grey Wolf": 40,
}

min_go_weight_per_animal = {
    "Red Deer": 240,
    "Whitetail Deer": 100,
    "Black Bear": 290,
    "Moose": 620,
}

max_go_weight_per_animal = {
    "Red Deer": 260,
    "Whitetail Deer": 110,
    "Black Bear": 409,
    "Moose": 700,
}

min_go_tr_per_animal = {
    "Red Deer": 272,
    "Whitetail Deer": 310,
    "Black Bear": 24,
    "Moose": 275,
}

max_go_tr_per_animal = {
    "Red Deer": 285,
    "Whitetail Deer": 650,
    "Black Bear": 28,
    "Moose": 320,
}
